.PHONY: clean All

All:
	@echo "----------Building project:[ SendMixedPcapApp - Release ]----------"
	@cd "SendMixedPcapApp" && "$(MAKE)" -f  "SendMixedPcapApp.mk"
clean:
	@echo "----------Cleaning project:[ SendMixedPcapApp - Release ]----------"
	@cd "SendMixedPcapApp" && "$(MAKE)" -f  "SendMixedPcapApp.mk" clean
